# This workflow will build an omod file using Maven, create a new release and add the file to the release.

name: Build and Release OMOD File

on:
 push:
  tags:
    - '*'
 workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Create New Release
      id: create_release
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
    - name: Add OMOD file to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: /home/runner/work/blopup-file-upload-module/blopup-file-upload-module/omod/target/blopup.fileupload.module-1.0.0.omod
        asset_name: omod-1.0-SNAPSHOT.omod
        asset_content_type: application/zip
