# This workflow will build an omod file using Maven, create a new release and add the file to the release.

name: Build and Release OMOD File

on:
 push:
  tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'zulu'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Execute tests
      run: mvn test
    - name: Create New Release
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        artifacts: |
          /home/runner/work/blopup-file-upload-module/blopup-file-upload-module/omod/target/blopup.fileupload-$(yq '.project.version' pom.xml).omod
